### ISSUE TITLE
 Docker build fails

### ISSUE THREAD

**Issue by rcemper** [intersystems-ib/workshop-pex#1]
#12 [builder 6/6] RUN javac -classpath /tmp/app/jar/*:/tmp/app/jgw/* workshop/pex/*.java &&     jar -cvf /tmp/app/
jar/FirstDemo.jar workshop/pex/*.class
#12 1.323 workshop/pex/FirstMessage.java:3: error: package com.intersystems.enslib.pex does not exist
#12 1.323 import com.intersystems.enslib.pex.*;
#12 1.323 ^
#12 1.327 workshop/pex/FirstMessage.java:8: error: cannot find symbol
#12 1.328 public class FirstMessage extends Message {
#12 1.328                                   ^
#12 1.328   symbol: class Message
#12 1.335 workshop/pex/FirstOperation.java:3: error: package com.intersystems.enslib.pex does not exist
#12 1.335 import com.intersystems.enslib.pex.*;
#12 1.335 ^
#12 1.335 workshop/pex/FirstOperation.java:10: error: cannot find symbol

**Comment by albertoft** [comment]
Yes, it was caused non-recent IRIS version. I've just committed a fix.
Thanks!
